baseURL = 'https://www.maurotaraborelliphoto.com/'
languageCode = 'en-US'
title = 'Mauro Taraborelli Photography'
disableKinds = ['rss']

[permalinks]
blog = '/:section/:year/:month/:title/'

[params]
description = '''Mauro Taraborelli's Photography Portfolio and Blog'''
photosBaseURL = 'https://media.maurotaraborelliphoto.com/photos/'

[params.author]
name = 'Mauro Taraborelli'
email = 'mauro@maurotaraborelliphoto.com'

[taxonomies]
  tag = 'tags'
  gallery = 'galleries'
  phototag = 'phototags'

[outputs]
  home = ['html', 'json']
  page = ['html']
  section = ['html', 'json']
  taxonomy = ['html']
  term = ['html', 'json']

[menus]
  [[menu.main]]
    name = 'home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'galleries'
    url = '/galleries/'
    weight = 2
  [[menu.main]]
    name = 'blog'
    identifier = 'blog'
    url = '/blog/'
    weight = 3
  [[menu.main]]
    name = 'about'
    url = '/about/'
    weight = 4